### ISSUE TITLE
Limited article length.

### ISSUE THREAD

**Issue by IshwarKanse** [Matterwiki/Matterwiki#16]
There seems to be a limit on article length. For testing I copied this https://www.digitalocean.com/community/tutorials/how-to-set-up-multi-factor-authentication-for-ssh-on-ubuntu-16-04 Digital Ocean article in a new wiki article. Less than half of the article was published. It would be great if there is no limit on the article length.

**Comment by nshntarora** [comment]
Hi! @IshwarKanse 
There is actually no limit on the article body. 
I just noticed that the problem is with Trix (the text editor matterwiki uses) parsing the HTML wrong. Due to some reason it reads the HTML markup and finds an end in the middle.

Though if you write directly in the editor there is no limit.

I've created an issue in the Trix repo for this.
[Basecamp/Trix Issue #359](https://github.com/basecamp/trix/issues/359)

**Comment by IshwarKanse** [comment]
Thanks @nshntarora , hope they get it closed soon. :)

**Comment by Agezao** [comment]
Fixed with PR: https://github.com/Matterwiki/Matterwiki/pull/33
I tested on my environment and everything went well.
@IshwarKanse can you test it again please?

**Comment by IshwarKanse** [comment]
Tested, working well for me too. :+1:
