### ISSUE TITLE
Switch bcrypt to bcryptjs

### ISSUE THREAD

**Issue by pixiefrog** [Matterwiki/Matterwiki#35]
I develop on windows and i've had problems with bcrypt pretty much every time it's used, can't even install it properly. 

There's a library that is from what i've seen a drop-in replacement with zero dependencies (bcrypt has gigs of them for windows users and then even those don't work properly). 

After a bit of frustration with trying to use bcrypt yet again, i decided to just uninstall it from my matterwiki installation, replaced it with bcryptjs, changed the 3 requires and it's working now.

Just thought i'd leave it as a suggestion.

[bcrypt.js](https://github.com/dcodeIO/bcrypt.js)

**Comment by Agezao** [comment]
It's actually a well known problem at the bcrypt library, reported in a [lot of issues](https://github.com/kelektiv/node.bcrypt.js/issues/102) on their repo.
I've made a PR for this item. I found a pretty valid point since bcryptjs is just like bcrypt but without you needing to download a whole SDK to work with.

Every time I need to work with Matter on my windows machine I need to change bcrypt to bcryptjs, then change back to bcrypt to commit. :/

@nshntarora What do you think?

PR: https://github.com/Matterwiki/Matterwiki/pull/40

**Comment by Rushmead** [comment]
I can totally agree with what he's saying here, trying to use Bcrypt on windows is an absolute pain. +1

**Comment by Agezao** [comment]
Closed after PR: https://github.com/Matterwiki/Matterwiki/pull/40 being merged.
