### ISSUE TITLE
removing a user doesn't remove or reparent his articles

### ISSUE THREAD

**Issue by chrisDeFouRire** [Matterwiki/Matterwiki#62]
when a user is removed, Matterwiki should find a new user_id for his articles, or remove them altogether...

**Comment by nshntarora** [comment]
Yes, agreed. How about we move them to the Admin user (with id=1) and not delete them?

**Comment by chrisDeFouRire** [comment]
sounds like the best solution to me...

btw, I've encountered the bug when I had to remove/add a profile with articles, because I couldn't change his password from Safari as an admin (didn't try in Chrome, sorry)

**Comment by krishnagopinath** [comment]
How about this? Instead of deleting a user, if we could just _disable_ them, we'd get the following benefits :

* The articles get the correct attribution. We needn't move any articles anywhere. We could maybe throw in a :x: sign next to the user's name to indicate he/she is disabled. 
* We thus maintain a history of who has been in the team.
* If the user is brought back in, they could just be _enabled_ again. 

Later, we could add the feature where the admin could actually delete the user and move their articles to some other user.

Thoughts?

**Comment by nshntarora** [comment]
A fix is pushed to the `bug-fix` branch. Please see if we could improve on the code.

**Comment by nshntarora** [comment]
@krishnagopinath Disabling is actually the correct way to go about it. Let's move it to the to do list. For now, I've decided to go with moving as a temporary fix.
