### ISSUE TITLE
Open links in a new tab

### ISSUE THREAD

**Issue by krishnagopinath** [Matterwiki/Matterwiki#70]
Opening links in the wiki in a new tab instead of replacing the page that the user is currently reading. Thoughts?

**Comment by nshntarora** [comment]
I'm not sure if people would like it.
Instead I was thinking about making it easy for them to jump to another article.
Like, we could have a list of articles under the current article's topic in the sidebar and then the user could easily jump to another article.

What do you think?

**Comment by edel-ma** [comment]
@nshntarora you mean extract tags/ keywords from article, and match the related articles(That's quite easy)? But why people want to jump from the current article? 
If it's a workflow, the link could writes in the body?

**Comment by nshntarora** [comment]
@edel-ma I'm not talking about related articles from all categories.

Let's say you're reading an article in the Marketing topic.
Chances are, you're from the marketing team, you'd want to know/read more.
So instead of you going back to the Browse Articles section you could jump to the next article from the list of articles in the sidebar.

By this I don't mean to replace linking in the body.

#50

**Comment by krishnagopinath** [comment]
Closing this because #50 has all the info needed
